//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipingRockERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alergen
    {
        public int AlergenID { get; set; }
        public string Alergen1 { get; set; }
        public System.DateTime AlergenAddedDate { get; set; }
        public System.DateTime AlergenChangedDate { get; set; }
        public Nullable<System.DateTime> AlergenDeletedDate { get; set; }
        public int AlergenModifiedById { get; set; }
    }
}
