//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipingRockERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allergen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Allergen()
        {
            this.Vendor_RawMaterial_Allergen = new HashSet<Vendor_RawMaterial_Allergen>();
        }
    
        public int AllergenId { get; set; }
        public string Allergen1 { get; set; }
        public System.DateTime AllergenAddedDate { get; set; }
        public System.DateTime AllergenChangedDate { get; set; }
        public Nullable<System.DateTime> AllergenDeletedDate { get; set; }
        public int AllergenModifiedById { get; set; }
        public bool isDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vendor_RawMaterial_Allergen> Vendor_RawMaterial_Allergen { get; set; }
    }
}
