//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipingRockERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class BottlesPerCase
    {
        public int BottlesPerCaseId { get; set; }
        public int BottleId { get; set; }
        public int BoxId { get; set; }
        public int NumberOfBottlesUnWrapped { get; set; }
        public int NumberOfBottlesWrapped { get; set; }
        public System.DateTime BottlesPerCaseAddedDate { get; set; }
        public System.DateTime BottlesPerCaseChangedDate { get; set; }
        public Nullable<System.DateTime> BottlesPerCaseDeletedDate { get; set; }
        public int BottlesPerCaseModifiedById { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual Bottle2 Bottle2 { get; set; }
        public virtual Box Box { get; set; }
    }
}
