//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipingRockERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Box
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Box()
        {
            this.BottlesPerCases = new HashSet<BottlesPerCase>();
            this.FinishedGoods = new HashSet<FinishedGood>();
        }
    
        public int BoxId { get; set; }
        public System.Guid ItemGuid { get; set; }
        public string BoxItemKey { get; set; }
        public string BoxDescriptionShort { get; set; }
        public string BoxDescriptionMedium { get; set; }
        public string BoxDescriptionLong { get; set; }
        public int ItemStatusId { get; set; }
        public int ItemTypeId { get; set; }
        public int ItemSubTypeId { get; set; }
        public int QuantityPerLayer { get; set; }
        public decimal Height { get; set; }
        public int LayersHigh { get; set; }
        public int LayersMed { get; set; }
        public int LayersLow { get; set; }
        public int NumberBoxesHigh { get; set; }
        public int NumberBoxesMed { get; set; }
        public int NumberBoxesLow { get; set; }
        public System.DateTime BoxAddedDate { get; set; }
        public System.DateTime BoxChangedDate { get; set; }
        public Nullable<System.DateTime> BoxDeletedDate { get; set; }
        public int BoxModifiedById { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BottlesPerCase> BottlesPerCases { get; set; }
        public virtual ItemSubType ItemSubType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinishedGood> FinishedGoods { get; set; }
    }
}
