//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipingRockERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Brand()
        {
            this.FinishedGoods = new HashSet<FinishedGood>();
            this.ReportSorts = new HashSet<ReportSort>();
        }
    
        public int BrandID { get; set; }
        public string BrandCode { get; set; }
        public string Brand1 { get; set; }
        public System.DateTime BrandAddedDate { get; set; }
        public System.DateTime BrandChangedDate { get; set; }
        public Nullable<System.DateTime> BrandDeletedDate { get; set; }
        public int BrandModifiedById { get; set; }
        public bool isDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinishedGood> FinishedGoods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportSort> ReportSorts { get; set; }
    }
}
