//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipingRockERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bulk_QcTest
    {
        public int Bulk_QcTestId { get; set; }
        public int BulkId { get; set; }
        public int QcTestId { get; set; }
        public System.DateTime Bulk_QcTestAddedDate { get; set; }
        public System.DateTime Bulk_QcTestChangedDate { get; set; }
        public Nullable<System.DateTime> Bulk_QcTestDeletedDate { get; set; }
        public int Bulk_QcTestModifiedById { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual Bulk Bulk { get; set; }
        public virtual QcTest QcTest { get; set; }
    }
}
