//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipingRockERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cap
    {
        public int CapId { get; set; }
        public System.Guid ItemGUID { get; set; }
        public string CapItemKey { get; set; }
        public string CapDescription { get; set; }
        public string NeckSize { get; set; }
        public string CapColor { get; set; }
        public string CapLiner { get; set; }
        public System.DateTime CapAddedDate { get; set; }
        public System.DateTime CapChangedDate { get; set; }
        public Nullable<System.DateTime> CapDeletedDate { get; set; }
        public int CapModifiedById { get; set; }
    }
}
