//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipingRockERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinishedGood_Quarantine
    {
        public int FinishedGood_QuarantineId { get; set; }
        public int FinishedGoodId { get; set; }
        public int QuarantineId { get; set; }
        public System.DateTime FinishedGood_QuarantineAddedDate { get; set; }
        public System.DateTime FinishedGood_QuarantineChangedDate { get; set; }
        public Nullable<System.DateTime> FinishedGood_QuarantineDeletedDate { get; set; }
        public int FinishedGood_QuarantineModifiedById { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual FinishedGood FinishedGood { get; set; }
        public virtual Quarantine Quarantine { get; set; }
    }
}
