//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipingRockERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinishedGood_QcTest
    {
        public int FinishedGood_QcTestId { get; set; }
        public int FinishedGoodId { get; set; }
        public int QcTestId { get; set; }
        public System.DateTime FinishedGood_QcTestAddedDate { get; set; }
        public System.DateTime FinishedGood_QcTestChangedDate { get; set; }
        public Nullable<System.DateTime> FinishedGood_QcTestDeletedDate { get; set; }
        public int FinishedGood_QcTestModifiedById { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual FinishedGood FinishedGood { get; set; }
        public virtual QcTest QcTest { get; set; }
    }
}
