//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipingRockERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlobalSetting
    {
        public int GlobalSettingsId { get; set; }
        public string GlobalSettingsParent { get; set; }
        public string GlobalSettingsName { get; set; }
        public string GlobalSettingsValue { get; set; }
        public string GlobalSettingsDescription { get; set; }
        public System.DateTime GlobalSettingsAddedDate { get; set; }
        public System.DateTime GlobalSettingsChangedDate { get; set; }
        public Nullable<System.DateTime> GlobalSettingsDeletedDate { get; set; }
        public int GlobalSettingsModifiedById { get; set; }
        public bool isDeleted { get; set; }
    }
}
