//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipingRockERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemSubType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemSubType()
        {
            this.Boxes = new HashSet<Box>();
            this.PackagingComponents = new HashSet<PackagingComponent>();
        }
    
        public int ItemSubTypeId { get; set; }
        public int ItemTypeId { get; set; }
        public string ItemSubType1 { get; set; }
        public string ItemSubTypeCode { get; set; }
        public string ItemSubTypeDescription { get; set; }
        public decimal LossFactorInventory { get; set; }
        public decimal LossFactorCost { get; set; }
        public System.DateTime ItemSubTypeAddedDate { get; set; }
        public System.DateTime ItemSubTypeChangedDate { get; set; }
        public Nullable<System.DateTime> ItemSubTypeDeletedDate { get; set; }
        public int ItemSubTypeModifiedById { get; set; }
        public bool isDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Box> Boxes { get; set; }
        public virtual ItemType ItemType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackagingComponent> PackagingComponents { get; set; }
    }
}
