//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipingRockERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemView
    {
        public string ItemKey { get; set; }
        public string ItemType { get; set; }
        public string ItemTypeCode { get; set; }
        public string ItemTypeDetail { get; set; }
        public string ItemStatus { get; set; }
        public string ItemDescription { get; set; }
        public string ItemDescriptionShort { get; set; }
        public string ItemDescriptionLong { get; set; }
        public bool ReceivingBoxLabelsRequired { get; set; }
        public int ExpirationMonths { get; set; }
        public int RetestingMonths { get; set; }
        public decimal PctOfLifeForRetesting { get; set; }
        public string Purchase_UnitOfMeasure { get; set; }
        public string Purchase_UnitOfMeasureAbbreviation { get; set; }
        public string Stock_UnitOfMeasure { get; set; }
        public string Stock_UnitOfMeasureAbbreviation { get; set; }
        public string Production_UnitOfMeasure { get; set; }
        public string Production_UnitOfMeasureAbbreviation { get; set; }
        public string Sale_UnitOfMeasure { get; set; }
        public string Sale_UnitOfMeasureAbbreviation { get; set; }
        public string ItemForm { get; set; }
        public string StorageCondition { get; set; }
        public string StorageConditionDescription { get; set; }
        public string QcTest { get; set; }
    }
}
