//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipingRockERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.Bottles = new HashSet<Bottle>();
            this.FinishedGoods = new HashSet<FinishedGood>();
        }
    
        public int ItemId { get; set; }
        public string ItemKey { get; set; }
        public int ItemTypeId { get; set; }
        public int ItemTypeDetailId { get; set; }
        public string ItemDescription { get; set; }
        public string ItemDescriptionShort { get; set; }
        public string ItemDescriptionLong { get; set; }
        public int ItemStatusId { get; set; }
        public int PurchaseUnitOfMeasureId { get; set; }
        public int StockUnitOfMeasureId { get; set; }
        public int ProductionUnitOfMeasureId { get; set; }
        public int SaleUnitOfMeasureId { get; set; }
        public int ItemFormId { get; set; }
        public bool ReceivingBoxLabelsRequired { get; set; }
        public int StorageConditionId { get; set; }
        public int QcTestId { get; set; }
        public int ExpirationMonths { get; set; }
        public int RetestingMonths { get; set; }
        public decimal PctOfLifeForRetesting { get; set; }
        public int QuarantineTypeId { get; set; }
        public System.DateTime ItemAddedDate { get; set; }
        public System.DateTime ItemChangedDate { get; set; }
        public Nullable<System.DateTime> ItemDeletedDate { get; set; }
        public int ItemModifiedById { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bottle> Bottles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinishedGood> FinishedGoods { get; set; }
        public virtual ItemForm ItemForm { get; set; }
        public virtual ItemStatu ItemStatu { get; set; }
        public virtual ItemType ItemType { get; set; }
        public virtual QcTest QcTest { get; set; }
        public virtual QuarantineType QuarantineType { get; set; }
        public virtual StorageCondition StorageCondition { get; set; }
    }
}
