//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipingRockERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemType_SubTypeView
    {
        public string ItemType { get; set; }
        public string ItemTypeCode { get; set; }
        public string ItemTypeDescription { get; set; }
        public string ItemSubType { get; set; }
        public string ItemSubTypeCode { get; set; }
        public string ItemSubTypeDescription { get; set; }
        public decimal ItemSubTypeLossFactorInventory { get; set; }
        public decimal ItemSubTypeLossFactorCost { get; set; }
        public bool ItemSubTypeisDeleted { get; set; }
        public decimal ItemTypeLossFactorCost { get; set; }
        public decimal ItemTypeLossFactorInventory { get; set; }
        public bool ItemTypeisDeleted { get; set; }
    }
}
