//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipingRockERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemTypeDetail
    {
        public int ItemTypeDetailId { get; set; }
        public int ItemTypeId { get; set; }
        public string ItemTypeDetail1 { get; set; }
        public string ItemTypeDetailDescription { get; set; }
        public decimal LossFactorInventory { get; set; }
        public decimal LossFactorCost { get; set; }
        public System.DateTime ItemTypeDetailAddedDate { get; set; }
        public System.DateTime ItemTypeDetailChangedDate { get; set; }
        public Nullable<System.DateTime> ItemTypeDetailDeletedDate { get; set; }
        public int ItemTypeDetailModifiedById { get; set; }
    
        public virtual ItemType ItemType { get; set; }
    }
}
