//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipingRockERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemType()
        {
            this.Bulks = new HashSet<Bulk>();
            this.ItemSubTypes = new HashSet<ItemSubType>();
        }
    
        public int ItemTypeId { get; set; }
        public string ItemType1 { get; set; }
        public string ItemTypeCode { get; set; }
        public string ItemTypeDescription { get; set; }
        public decimal LossFactorCost { get; set; }
        public decimal LossFactorInventory { get; set; }
        public System.DateTime ItemTypeAddedDate { get; set; }
        public System.DateTime ItemTypeChangedDate { get; set; }
        public Nullable<System.DateTime> ItemTypeDeletedDate { get; set; }
        public int ItemTypeModifiedById { get; set; }
        public bool isDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bulk> Bulks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemSubType> ItemSubTypes { get; set; }
    }
}
