//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipingRockERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemView
    {
        public string ItemKey { get; set; }
        public string DescriptionLong { get; set; }
        public System.Guid ItemGUID { get; set; }
        public string ItemType { get; set; }
        public string ItemSubType { get; set; }
        public string ItemStatus { get; set; }
    }
}
