//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipingRockERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackagingUOM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PackagingUOM()
        {
            this.FinishedGoods = new HashSet<FinishedGood>();
        }
    
        public int PackagingUOMId { get; set; }
        public string PackagingUOM1 { get; set; }
        public string PackagingUOMAbbreviation { get; set; }
        public string PackagingUOMDesc { get; set; }
        public System.DateTime PackagingUOMAddedDate { get; set; }
        public System.DateTime PackagingUOMChangedDate { get; set; }
        public Nullable<System.DateTime> PackagingUOMDeletedDate { get; set; }
        public int PackagingUOMModifiedById { get; set; }
        public bool isDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinishedGood> FinishedGoods { get; set; }
    }
}
