//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipingRockERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackagingComponent
    {
        public int PackagingComponentId { get; set; }
        public string PackagingComponentItemKey { get; set; }
        public string PackagingComponentDescriptionShort { get; set; }
        public string PackagingComponentDescriptionMedium { get; set; }
        public string PackagingComponentDescriptionLong { get; set; }
        public int ItemStatusId { get; set; }
        public int ItemTypeId { get; set; }
        public int ItemSubTypeId { get; set; }
        public System.DateTime PackagingComponentAddedDate { get; set; }
        public System.DateTime PackagingComponentChangedDate { get; set; }
        public Nullable<System.DateTime> PackagingComponentDeletedDate { get; set; }
        public int PackagingComponentModifiedById { get; set; }
    
        public virtual ItemSubType ItemSubType { get; set; }
    }
}
