//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipingRockERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackagingLevel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PackagingLevel()
        {
            this.FinishedGoods = new HashSet<FinishedGood>();
        }
    
        public int PackagingLevelId { get; set; }
        public string PackagingLevel1 { get; set; }
        public string PackagingLevelAbbreviation { get; set; }
        public string PackagingLevelDesc { get; set; }
        public System.DateTime PackagingLevelAddedDate { get; set; }
        public System.DateTime PackagingLevelChangedDate { get; set; }
        public Nullable<System.DateTime> PackagingLevelDeletedDate { get; set; }
        public int PackagingLevelModifiedById { get; set; }
        public bool isDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinishedGood> FinishedGoods { get; set; }
    }
}
