//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipingRockERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportSort
    {
        public int ReportSortId { get; set; }
        public int BrandId { get; set; }
        public int Sort { get; set; }
        public string ReportSection { get; set; }
        public System.DateTime ReportSortAddedDate { get; set; }
        public System.DateTime ReportSortChangedDate { get; set; }
        public Nullable<System.DateTime> ReportSortDeletedDate { get; set; }
        public int ReportSortModifiedById { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual Brand Brand { get; set; }
    }
}
