//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipingRockERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Screen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Screen()
        {
            this.UserRoleAuthorities = new HashSet<UserRoleAuthority>();
        }
    
        public int ScreenId { get; set; }
        public string ScreenName { get; set; }
        public System.DateTime ScreenAddedDate { get; set; }
        public System.DateTime ScreenChangedDate { get; set; }
        public Nullable<System.DateTime> ScreenDeletedDate { get; set; }
        public int ScreenModifiedById { get; set; }
        public bool isDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRoleAuthority> UserRoleAuthorities { get; set; }
    }
}
