//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipingRockERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply
    {
        public int SupplyId { get; set; }
        public string SupplyItemKey { get; set; }
        public string SupplyDescriptionShort { get; set; }
        public string SupplyDescriptionMedium { get; set; }
        public string SupplyDescriptionLong { get; set; }
        public int ItemStatusId { get; set; }
        public int ItemTypeId { get; set; }
        public int ItemSubTypeId { get; set; }
        public int QuantityPerLayer { get; set; }
        public decimal Height { get; set; }
        public int LayersHigh { get; set; }
        public int LayersMed { get; set; }
        public int LayersLow { get; set; }
        public int NumberBoxesHigh { get; set; }
        public int NumberBoxesMed { get; set; }
        public int NumberBoxesLow { get; set; }
        public System.DateTime SupplyAddedDate { get; set; }
        public System.DateTime SupplyChangedDate { get; set; }
        public Nullable<System.DateTime> SupplyDeletedDate { get; set; }
        public int SupplyModifiedById { get; set; }
    
        public virtual ItemSubType ItemSubType { get; set; }
    }
}
