//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipingRockERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitOfMeasure
    {
        public int UnitOfMeasureId { get; set; }
        public string UnitOfMeasure1 { get; set; }
        public string UnitOfMeasureAbbreviation { get; set; }
        public Nullable<int> Ref_GDSN_UoMId { get; set; }
        public System.DateTime UnitOfMeasureAddedDate { get; set; }
        public System.DateTime UnitOfMeasureChangedDate { get; set; }
        public Nullable<System.DateTime> UnitOfMeasureDeletedDate { get; set; }
        public int UnitOfMeasureModifiedById { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual Ref_GDSN_UoM Ref_GDSN_UoM { get; set; }
    }
}
