//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipingRockERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.User_UserRole = new HashSet<User_UserRole>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> UserLastLoginDate { get; set; }
        public System.DateTime UserAddedDate { get; set; }
        public System.DateTime UserChangedDate { get; set; }
        public Nullable<System.DateTime> UserDeletedDate { get; set; }
        public int UserModifiedById { get; set; }
        public bool isDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_UserRole> User_UserRole { get; set; }
    }
}
