//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipingRockERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_UserRole
    {
        public int User_UserRoleId { get; set; }
        public int UserId { get; set; }
        public int UserRoleId { get; set; }
        public System.DateTime User_UserRoleAddedDate { get; set; }
        public System.DateTime User_UserRoleChangedDate { get; set; }
        public Nullable<System.DateTime> User_UserRoleDeletedDate { get; set; }
        public int User_UserRoleModifiedById { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual User User { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
