//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipingRockERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserRole()
        {
            this.User_UserRole = new HashSet<User_UserRole>();
            this.UserRole_UserRoleAuthority = new HashSet<UserRole_UserRoleAuthority>();
        }
    
        public int UserRoleId { get; set; }
        public string UserRoleName { get; set; }
        public System.DateTime UserRoleAddedDate { get; set; }
        public System.DateTime UserRoleChangedDate { get; set; }
        public Nullable<System.DateTime> UserRoleDeletedDate { get; set; }
        public int UserRoleModifiedById { get; set; }
        public bool isDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_UserRole> User_UserRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRole_UserRoleAuthority> UserRole_UserRoleAuthority { get; set; }
    }
}
