//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipingRockERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole_UserRoleAuthority
    {
        public int UserRole_UserRoleAuthorityId { get; set; }
        public int UserRoleId { get; set; }
        public int UserRoleAuthorityId { get; set; }
        public System.DateTime UserRole_UserRoleAuthorityAddedDate { get; set; }
        public System.DateTime UserRole_UserRoleAuthorityChangedDate { get; set; }
        public Nullable<System.DateTime> UserRole_UserRoleAuthorityDeletedDate { get; set; }
        public int UserRole_UserRoleAuthorityModifiedById { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual UserRole UserRole { get; set; }
        public virtual UserRoleAuthority UserRoleAuthority { get; set; }
    }
}
