//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipingRockERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRoleAuthority
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserRoleAuthority()
        {
            this.UserRole_UserRoleAuthority = new HashSet<UserRole_UserRoleAuthority>();
        }
    
        public int UserRoleAuthorityId { get; set; }
        public Nullable<int> ScreenId { get; set; }
        public string FeatureDescription { get; set; }
        public Nullable<bool> CanView { get; set; }
        public Nullable<bool> CanEdit { get; set; }
        public Nullable<bool> CanCreate { get; set; }
        public Nullable<bool> CanDelete { get; set; }
        public Nullable<bool> CanUnDelete { get; set; }
        public Nullable<bool> CanDoAll { get; set; }
        public System.DateTime UserRoleAuthorityAddedDate { get; set; }
        public System.DateTime UserRoleAuthorityChangedDate { get; set; }
        public Nullable<System.DateTime> UserRoleAuthorityDeletedDate { get; set; }
        public int UserRoleAuthorityModifiedById { get; set; }
        public bool isDeleted { get; set; }
    
        public virtual Screen Screen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRole_UserRoleAuthority> UserRole_UserRoleAuthority { get; set; }
    }
}
