//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipingRockERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vBatchMaster_Location
    {
        public string Itemkey { get; set; }
        public string Location { get; set; }
        public string Inclasskey { get; set; }
        public string Statuscode { get; set; }
        public Nullable<System.DateTime> Effectivedate { get; set; }
        public string Spare1 { get; set; }
        public string Physinprogress { get; set; }
        public Nullable<System.DateTime> Physinitdate { get; set; }
        public string Spare2 { get; set; }
        public Nullable<System.DateTime> Physcompletedate { get; set; }
        public string Spare3 { get; set; }
        public decimal Marketcost { get; set; }
        public Nullable<decimal> Reordercost { get; set; }
        public Nullable<decimal> Carrycost { get; set; }
        public Nullable<decimal> Stdcost { get; set; }
        public Nullable<decimal> Avgcost { get; set; }
        public Nullable<decimal> Lstcost { get; set; }
        public Nullable<System.DateTime> LstSystemcostdate { get; set; }
        public Nullable<decimal> Distcost { get; set; }
        public Nullable<decimal> Baseprice { get; set; }
        public Nullable<double> Qtyonhand { get; set; }
        public Nullable<double> Qtyoversold { get; set; }
        public Nullable<double> Qtyonorder { get; set; }
        public Nullable<double> Qtytrnin { get; set; }
        public Nullable<double> Qtytrnout { get; set; }
        public Nullable<double> Qtycommitsales { get; set; }
        public Nullable<double> Qtycommitprod { get; set; }
        public Nullable<double> Qtypoindir { get; set; }
        public Nullable<double> Qtyoeindir { get; set; }
        public Nullable<System.DateTime> Reordqtydate { get; set; }
        public string Spare4 { get; set; }
        public Nullable<System.DateTime> Maxordqtydate { get; set; }
        public string Reserved5 { get; set; }
        public string Pamsstat { get; set; }
        public string Binno { get; set; }
        public Nullable<double> Weightperunit { get; set; }
        public string Weightdesc { get; set; }
        public string Revacct { get; set; }
        public string Cogsacct { get; set; }
        public Nullable<System.DateTime> Pamsstatdate { get; set; }
        public Nullable<System.DateTime> Basepricedate { get; set; }
        public Nullable<System.DateTime> Marketcostdate { get; set; }
        public Nullable<System.DateTime> Reordercostdate { get; set; }
        public Nullable<System.DateTime> Carrycostdate { get; set; }
        public Nullable<System.DateTime> Stdcostdate { get; set; }
        public Nullable<System.DateTime> Minstkqtydate { get; set; }
        public Nullable<System.DateTime> Maxstkqtydate { get; set; }
        public Nullable<double> Basepriceopratncrncy { get; set; }
        public Nullable<double> Basepriceitemcrncy { get; set; }
        public Nullable<double> Lstcostopratncrncy { get; set; }
        public Nullable<double> Lstcostitemcrncy { get; set; }
        public Nullable<double> Avgcostopratncrncy { get; set; }
        public Nullable<double> Avgcostitemcrncy { get; set; }
        public string Incommkey { get; set; }
        public string Salestaxkey { get; set; }
        public string Reserveda { get; set; }
        public Nullable<double> Minstockqty { get; set; }
        public Nullable<double> Maxstockqty { get; set; }
        public Nullable<double> Reorderqty { get; set; }
        public Nullable<double> Maxorderqty { get; set; }
        public Nullable<double> Reserved6 { get; set; }
        public string Primevend { get; set; }
        public string Purchtaxkey { get; set; }
        public string Recuserid { get; set; }
        public Nullable<System.DateTime> Recdate { get; set; }
        public string COGSAdjAcct { get; set; }
        public string Spare { get; set; }
        public double SerLotQty { get; set; }
        public double InspQty { get; set; }
        public double ReciptQty { get; set; }
        public string Item_Type { get; set; }
        public string Routing_Code { get; set; }
        public Nullable<byte> Low_Lvl_Code { get; set; }
        public Nullable<short> Order_Lead_Time { get; set; }
        public Nullable<System.DateTime> MRP_Last_Run { get; set; }
        public Nullable<byte> Item_Exists { get; set; }
        public Nullable<double> MaxAmtOnLoc { get; set; }
        public Nullable<System.DateTime> AvgCalculatedDate { get; set; }
        public Nullable<double> AvgDailyLocAmt { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public Nullable<short> DaysOnLocAtzero { get; set; }
        public Nullable<double> TotAmtInSys { get; set; }
        public string OverrideMaxStkQty { get; set; }
        public string BuyerID { get; set; }
        public string IssueBinNo { get; set; }
        public string ProductionBinNo { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUserID { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyUserID { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public Nullable<System.DateTime> User6 { get; set; }
        public Nullable<double> User7 { get; set; }
        public Nullable<double> User8 { get; set; }
        public Nullable<decimal> User9 { get; set; }
        public Nullable<decimal> User10 { get; set; }
        public Nullable<int> User11 { get; set; }
        public Nullable<int> User12 { get; set; }
        public string ESG_REASON { get; set; }
        public string ESG_APPROVER { get; set; }
        public Nullable<bool> CUSTOM1 { get; set; }
        public Nullable<bool> CUSTOM2 { get; set; }
        public Nullable<bool> CUSTOM3 { get; set; }
        public Nullable<bool> CUSTOM4 { get; set; }
        public Nullable<bool> CUSTOM5 { get; set; }
        public Nullable<bool> CUSTOM6 { get; set; }
        public Nullable<bool> CUSTOM7 { get; set; }
        public Nullable<bool> CUSTOM8 { get; set; }
        public Nullable<bool> CUSTOM9 { get; set; }
        public Nullable<bool> CUSTOM10 { get; set; }
    }
}
