//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipingRockERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vBatchMaster_Item
    {
        public string Itemkey { get; set; }
        public string Desc1 { get; set; }
        public string Desc2 { get; set; }
        public string Reserved1 { get; set; }
        public Nullable<double> PurchconvFctr { get; set; }
        public Nullable<double> PurchToStkCnvFctr { get; set; }
        public Nullable<double> SaleToStkCnvFctr { get; set; }
        public bool UseGenCnvFctr { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<short> Physcyclecnt { get; set; }
        public string Seriallotflg { get; set; }
        public string NumberMask { get; set; }
        public Nullable<double> DefltSize { get; set; }
        public Nullable<short> DaysToExpire { get; set; }
        public string Itemtyp { get; set; }
        public string ItemSubtyp { get; set; }
        public string Itemcostmthd { get; set; }
        public string Oversoldcostmthd { get; set; }
        public string PriceGrp { get; set; }
        public string Abckey { get; set; }
        public string Manufacturer { get; set; }
        public string Altitemkey { get; set; }
        public string Prodkey { get; set; }
        public string Commodkey { get; set; }
        public string Eccncode { get; set; }
        public Nullable<double> Itemlength { get; set; }
        public Nullable<double> Itemwidth { get; set; }
        public Nullable<double> Itemheight { get; set; }
        public string Inctrlcode { get; set; }
        public string Plannercode { get; set; }
        public string Spare1 { get; set; }
        public string Orderpolicycode { get; set; }
        public Nullable<double> Orderpoint { get; set; }
        public Nullable<short> Mrptrigger { get; set; }
        public Nullable<double> Minorderqty { get; set; }
        public Nullable<double> Maxorderqty { get; set; }
        public Nullable<double> Rndfctr { get; set; }
        public string Safetystockcode { get; set; }
        public Nullable<double> Safetystockqty { get; set; }
        public string Stockuomcode { get; set; }
        public string Purchaseuomcode { get; set; }
        public string Salesuomcode { get; set; }
        public string Itemlinearuom { get; set; }
        public Nullable<double> Yieldfctr { get; set; }
        public string Spare2 { get; set; }
        public Nullable<short> Forecasttmfence { get; set; }
        public Nullable<short> Planningtmfence { get; set; }
        public string Pegindicator { get; set; }
        public string Backflush { get; set; }
        public Nullable<short> Levelcode { get; set; }
        public Nullable<short> Leadtime { get; set; }
        public string OrderMethod { get; set; }
        public string Reservedmfg { get; set; }
        public string Recuserid { get; set; }
        public Nullable<System.DateTime> Recdate { get; set; }
        public string Operatcrncyky { get; set; }
        public string Altstockuom { get; set; }
        public Nullable<double> NAStubUnPrc { get; set; }
        public Nullable<double> NAStunUnCst { get; set; }
        public string Taxrefid { get; set; }
        public string Spare3 { get; set; }
        public string Insp_YN { get; set; }
        public string MSDSTemp_Key { get; set; }
        public Nullable<double> SpecGravity { get; set; }
        public string Inter_Typ { get; set; }
        public string MeasuredBy { get; set; }
        public string LotSizingMthd { get; set; }
        public string BoilingPoint { get; set; }
        public string CASnbr { get; set; }
        public string ChemicalName { get; set; }
        public string DelayedHealthHazard { get; set; }
        public string FireHazard { get; set; }
        public string FlashPoint { get; set; }
        public string FlashPointMethod { get; set; }
        public string Gas { get; set; }
        public string HMISChronic { get; set; }
        public string HMISFlammability { get; set; }
        public string HMISHealth { get; set; }
        public string HMISPersProt { get; set; }
        public string HMISReactivity { get; set; }
        public string ImmedHealthHaz { get; set; }
        public string Liquid { get; set; }
        public string LowerExplosiveLimit { get; set; }
        public string MatClassifications { get; set; }
        public string Mixture { get; set; }
        public string Pure { get; set; }
        public string ReactivityHazard { get; set; }
        public string Solid { get; set; }
        public string SuddenRlsOfPress { get; set; }
        public string TradeSecret { get; set; }
        public string UpperExplosiveLimit { get; set; }
        public string VPmmHg { get; set; }
        public string VPTemp { get; set; }
        public string OtherInfo { get; set; }
        public string Salsp_Com_Ky { get; set; }
        public string SalesQC { get; set; }
        public string MfgQC { get; set; }
        public string AdditionalComm { get; set; }
        public Nullable<System.DateTime> CommEffectDate { get; set; }
        public Nullable<System.DateTime> CommExpDate { get; set; }
        public string PSrLotAutoGen { get; set; }
        public Nullable<short> PCustomPosition { get; set; }
        public string POptional { get; set; }
        public string PCustom { get; set; }
        public string PDateFormat { get; set; }
        public Nullable<int> PSeqNo { get; set; }
        public string MSrLotAutoGen { get; set; }
        public Nullable<short> MCustomPosition { get; set; }
        public string MOptional { get; set; }
        public string MCustom { get; set; }
        public string MDateFormat { get; set; }
        public Nullable<int> MSeqNo { get; set; }
        public string MultipleBinsReq { get; set; }
        public string LotIssueMethod { get; set; }
        public Nullable<bool> PUseSeqNo { get; set; }
        public Nullable<bool> MUseSeqNo { get; set; }
        public Nullable<short> DaysToQuarantine { get; set; }
        public string INCI { get; set; }
        public string EINICS { get; set; }
        public string Produomcode { get; set; }
        public Nullable<int> ShipShLife { get; set; }
        public Nullable<int> ProdShLife { get; set; }
        public Nullable<bool> FGExpShLife { get; set; }
        public string UPCCODE { get; set; }
        public string StrgCndtnKey { get; set; }
        public string PrintableDesc { get; set; }
        public Nullable<int> PurShelfLife { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUserID { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyUserID { get; set; }
        public string AllowSerialization { get; set; }
        public string AllowPartIssueSerialization { get; set; }
        public Nullable<int> Purchasable { get; set; }
        public Nullable<int> Saleable { get; set; }
        public Nullable<double> DefaultContainerQty { get; set; }
        public string PurQCType { get; set; }
        public string SpecificationTemplate { get; set; }
        public string NFPA1 { get; set; }
        public string NFPA2 { get; set; }
        public string NFPA3 { get; set; }
        public string NFPA4 { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public Nullable<System.DateTime> User6 { get; set; }
        public Nullable<double> User7 { get; set; }
        public Nullable<double> User8 { get; set; }
        public Nullable<decimal> User9 { get; set; }
        public Nullable<decimal> User10 { get; set; }
        public Nullable<int> User11 { get; set; }
        public Nullable<int> User12 { get; set; }
        public string ESG_REASON { get; set; }
        public string ESG_APPROVER { get; set; }
        public string CUSTOM1 { get; set; }
        public string CUSTOM2 { get; set; }
        public string CUSTOM3 { get; set; }
        public string CUSTOM4 { get; set; }
        public string CUSTOM5 { get; set; }
        public string CUSTOM6 { get; set; }
        public string CUSTOM7 { get; set; }
        public Nullable<bool> CUSTOM8 { get; set; }
        public Nullable<bool> CUSTOM9 { get; set; }
        public Nullable<bool> CUSTOM10 { get; set; }
        public string DfltCntBOM { get; set; }
        public string AllowPalletization { get; set; }
        public string ClassificationID { get; set; }
    }
}
