//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipingRockERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class vBatchMaster_BOM
    {
        public string ParentItemKey { get; set; }
        public string ItemKey { get; set; }
        public string LocationKey { get; set; }
        public Nullable<decimal> StdCost { get; set; }
        public Nullable<double> QtyInStockUOM { get; set; }
        public Nullable<decimal> AvgCost { get; set; }
        public string StockUOM { get; set; }
        public string FormulaId { get; set; }
        public string MakeFormulaId { get; set; }
        public string FillIn { get; set; }
        public string MakeFillIn { get; set; }
        public Nullable<int> LineNum { get; set; }
        public string AssemblyType { get; set; }
        public double ParFillLevel { get; set; }
        public Nullable<double> Filllevel { get; set; }
        public string FillUOM { get; set; }
        public double LossPcnt { get; set; }
        public string MakeBuy { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public Nullable<double> DispQty { get; set; }
        public string DispUOM { get; set; }
        public string ItemTyp { get; set; }
        public string ItemSubTyp { get; set; }
    }
}
