//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PipingRockERP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vendor()
        {
            this.Vendor_RawMaterial = new HashSet<Vendor_RawMaterial>();
        }
    
        public int VendorId { get; set; }
        public string VendorKey { get; set; }
        public string VendorName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string StateProvinceCode { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string DollarOrPercentVolumnDiscount { get; set; }
        public System.DateTime VendorAddedDate { get; set; }
        public System.DateTime VendorChangedDate { get; set; }
        public Nullable<System.DateTime> VendorDeletedDate { get; set; }
        public int VendorModifiedById { get; set; }
        public bool isDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vendor_RawMaterial> Vendor_RawMaterial { get; set; }
    }
}
